version: '3'

services:
  nginx:
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    restart: always
    ports:
      - "80:80"
    volumes: 
      - type: bind 
        source: ${PWD}/www/src/
        target: /usr/share/nginx/html/
      - type: bind
        source: ./nginx/default.conf
        target: /etc/nginx/conf.d/default.conf

  www: 
    user: 1000:1000
    build:
      context: ./www
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: ./www/src/
        target: /usr/share/nginx/html/

  pg-db:
    build: 
      context: ./db
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./db/pg_data:/var/lib/postgresql/data
      - pg_data:/var/lib/postgresql/data


volumes:
  pg_data:
    name: 'pg_data'